### ISSUE TITLE
Advertise GSoC Projects / Contributor Search in general

### ISSUE THREAD

**Issue by gedankenstuecke** [openSNP/snpr#268]
If the GSoC application is merged we need to act fast to get the word out. Where should we advertise our search for 1-n students? 

* Our Newsletter? 
* Social Media
* Study Groups? 
* Your Idea here

**Comment by philippbayer** [comment]
I think the biggest reach comes from GSOC's own announcement, newsletter sounds good too!

other places to advertise:

* COMBINE
* reddit.com/r/bioinformatics
* biostars forum
* seqanswers? can't find precedent in their forums, may get deleted
* www.bioinformatics.org has announcements

I also just found this, may be useful: http://up-for-grabs.net/#/

**Comment by gedankenstuecke** [comment]
GSOCs advertisement won't lead people to our projects and those we should advertise, because if there are no students having an interest in the different projects we won't have anybody working on them? :wink: 

COMBINE sounds good to me, the others too. Maybe @acabunoc and @auremoser have some ideas?

**Comment by auremoser** [comment]
Hmm, I'm not sure I fully understand the first question, but maybe that's because my experience with GSOC is minimal. 

* perhaps the [COS](http://opensciences.org/) would advertise on their blog
* maybe the [FORCE16](https://www.force11.org/) conference would push it out to their community? @acabunoc, what do you think? 
* you could probably also post it on google fora like [Open Science Framework](https://groups.google.com/forum/#!forum/openscienceframework), or the [Open Genomics Forum](http://genomicsforum.org/). 
* we could spread the word at the [GET Conference](http://www.getconference.org/) next month too, or if that's too far away, Abby and I will be there.

**Comment by gedankenstuecke** [comment]
Sorry for being confusing. Students have to apply to specific projects, so just being listed on GSoC won't do any good without advertising to specific students. _FORCE_ and _GET_ are good ideas but too far in the future unfortunately, the deadline for applications is March 25th iirc, so it's a bit urgent (as always :wink:). The Google Fora are a good idea though, will do that as well as the open science and DIYBio mailing lists. 

And now I really wanna go to GET, knowing that Abby and you'll be there!

**Comment by acabunoc** [comment]
Getting on the official GSoC page is great! That's usually how I find students (rather, they find me...).

Some place actually made a job posting for GSoC positions:
http://bioinformatics.ca/resources/jobs/google-summer-code-0

**Comment by gedankenstuecke** [comment]
Great, I did some advertising for the whole OBF organisation on the DIYBio and OKF-OpenScience mailing lists :+1:

**Comment by gedankenstuecke** [comment]
Ok, I think we can close this. No more advertising to do, just :pray: :smiley:
