### ISSUE TITLE
Vivek Rai: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by vivekiitkgp** [openSNP/snpr#276]
I have had the opportunity to talk to Bastion, Philipp and other members through GSoC discussion. In process, I became aware of the roadmap of the project and would like to contribute to key improvement areas of the project.

On, by the way, I'll be graduating next year with a major in Biotechnology. I write at shorts (https://vivekiitkgp.github.io).<p><br><blockquote>This issue was created by @vivekiitkgp via <a href='https://mozillascience.org/collaborate'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by philippbayer** [comment]
Hi Vivek!
Welcome to openSNP :) We haven't heard back from GSoC yet, the deadline to assign slots for students is tomorrow. You're of course more than welcome to contribute outside of GSoC, but better to wait a few days until Google tells us how many (if any) slots we get so that contributors don't step on each others' toes.

**Comment by vivekiitkgp** [comment]
Hey Philip,p,

This post indicates my general non-GSoC interest to contribute to this
project! :) I will get back to this project anyway once done with college
exams.

Thanks!

--
https://vivekiitkgp.github.io

**Comment by gedankenstuecke** [comment]
Hey @vivekiitkgp glad to hear you're interested in participating outside of GSoC too! All the best for your exams and let's talk about good ways to start contributing once you're done with them 😄

**Comment by vivekiitkgp** [comment]
Guess time to close this! :)
