### ISSUE TITLE
Language Checking

### ISSUE THREAD

**Issue by gedankenstuecke** [openSNP/snpr#359]
None of the main contributors to openSNP is a native speaker. So there'll be lots of typos and/or grammatical sins in the texts on our website. Looking through those and fixing them would be great.
 ❤️

**Comment by amiefairs** [comment]
I'm getting on this as my first contribution to #mozsprint 2017!

**Comment by amiefairs** [comment]
Ok here are some comments starting with the FAQs page for English:

- [ ] title should say 'What does OpenSNP offer me as a genotyping-customer?
' -> delete the final 's'

- [ ] first line should say 'If you _were_ genotyped by 23andMe, deCODEme...'

- [ ] in the third paragraph it sounds more normal to say 'You can also publish some of your phenotypes so, someday, it might _be_ possible to associate some SNPs with phenotypes...' (though 'become' is not actually wrong)

- [ ] in the Who is behind this? section, you don't need the hyphen between master-progammes in 'Bastian and Philipp did their undergraduate studies in Life Sciences and are currently doing their master-programmes'. It actually sounds more normal to say 'Master's degrees'.

- [ ] the following line says you are doing your PhDs -> how are you doing your Masters and a PhD at the same time...?

- [ ] change 'Helge is the only “real” web developer on the team and has helped us a lot in testing _many_ of the things we did.'

- [ ] in the Why all this? section, change 'openSNP is a non-profit, open-source project that is about sharing _genetic_ and phenotypic information.' -> delete the 'al'

 - [ ] change 'The idea _for_ this project came to Bastian after he was genotyped by 23andMe ...'

 - [ ] change the title 'How much does membership in openSNP cost?' -> delete the 'a'

 - [ ] change 'We take the "open" in openSNP _seriously_, so everything is free of charge.'

- [ ] in the Exomes? section change 'If _you have had_ your exome sequenced through 23andMe ...'

- [ ] in the I was gentoyped by another company... section, change 'If your company is missing up to now it is because we did not have an example-file...' -> delete the comma between 'is' and 'because'

**Comment by amiefairs** [comment]
In your README:

- [ ] under the Contributing to openSNP section it says 'We also have a ROADMAP.md, containing your idea of where the project should head....' -> I am assuming that 'your' should be 'our'?

- [ ] in the same section, change 'May you be celebrated, inside our humans.txt and _outside_ of it!'

**Comment by gedankenstuecke** [comment]
@amiefairs Awesome, thanks so much! 

![](https://media.giphy.com/media/xUPGcxpCV81ebKh7Vu/giphy.gif)

For the markdown files like `ROADMAP.md`, `INSTALL.md` you can go ahead and do edits on those right away. There will be no (major) conflicts I guess. Just the `*.html.erb` are the ones that @philippbayer is overhauling right now. 🙂

**Comment by gedankenstuecke** [comment]
The FAQ related items are now part of #365 and will be live with the new page layout. 👍

**Comment by gedankenstuecke** [comment]
Okay, he big PR is now merged. Front-end changes can now be directly done through new pull requests. 👍 🎉

**Comment by gedankenstuecke** [comment]
Thanks again for all the help. Closed for now. 💖
